import { NotificationStatus } from '@/generated/prisma/browser';

import { Badge } from '@/components/ui/badge';
import { db } from '@/lib/db/client';

import { AdminPageShell } from '../_components/admin-page-shell';
import { AdminStatCard } from '../_components/admin-stat-card';
import { requireAdminUser } from '../require-admin-user';

export default async function AdminNotificationsPage() {
  await requireAdminUser();

  const now = Date.now();
  const sevenDaysAgo = new Date(now - 7 * 24 * 60 * 60 * 1000);

  const [
    totalNotifications,
    pendingNotifications,
    failedNotifications,
    unreadNotifications,
    notifications7d,
    recentNotifications,
  ] = await Promise.all([
    db.notification.count(),
    db.notification.count({ where: { status: NotificationStatus.PENDING } }),
    db.notification.count({ where: { status: NotificationStatus.FAILED } }),
    db.notification.count({ where: { isRead: false } }),
    db.notification.count({ where: { createdAt: { gte: sevenDaysAgo } } }),
    db.notification.findMany({
      orderBy: { createdAt: 'desc' },
      take: 20,
      select: {
        createdAt: true,
        id: true,
        isRead: true,
        status: true,
        title: true,
        type: true,
        user: {
          select: {
            email: true,
          },
        },
      },
    }),
  ]);

  const failedRate =
    totalNotifications > 0
      ? Math.round((failedNotifications / totalNotifications) * 100)
      : 0;

  return (
    <AdminPageShell
      title="Notifications"
      description="Observe delivery health, unread load, and platform alert volume."
    >
      <div className="grid grid-cols-1 gap-4 md:grid-cols-2 xl:grid-cols-5">
        <AdminStatCard
          title="Total Notifications"
          value={totalNotifications.toLocaleString()}
        />
        <AdminStatCard
          title="Pending Queue"
          value={pendingNotifications.toLocaleString()}
        />
        <AdminStatCard
          title="Unread"
          value={unreadNotifications.toLocaleString()}
        />
        <AdminStatCard
          title="Delivery Failures"
          value={failedNotifications.toLocaleString()}
        />
        <AdminStatCard
          title="Failure Rate"
          value={`${failedRate}%`}
          helperText={`${notifications7d.toLocaleString()} created in 7d`}
        />
      </div>

      <div>
        <h2 className="text-lg font-semibold">Recent Events</h2>
        <p className="mb-4 text-sm text-muted-foreground">
          Latest 20 notifications emitted by the platform.
        </p>

        {recentNotifications.length === 0 ? (
          <p className="py-8 text-center text-sm text-muted-foreground">
            No notifications yet. Notifications are generated by platform events
            like scrape completions, application updates, and system alerts.
          </p>
        ) : (
          <div className="grid grid-cols-1 gap-3 md:grid-cols-2">
            {recentNotifications.map(notification => (
              <div
                key={notification.id}
                className="rounded-lg border border-border/60 p-4"
              >
                <div className="flex items-start justify-between gap-2">
                  <p className="truncate font-medium">{notification.title}</p>
                  <div className="flex shrink-0 items-center gap-1.5">
                    <Badge variant="outline">{notification.status}</Badge>
                    {!notification.isRead ? (
                      <Badge variant="secondary">Unread</Badge>
                    ) : null}
                  </div>
                </div>
                <div className="mt-1.5 flex items-center gap-2 text-xs text-muted-foreground">
                  <span>{notification.type}</span>
                  <span>·</span>
                  <span>{notification.user.email}</span>
                  <span>·</span>
                  <span>
                    {new Date(notification.createdAt).toLocaleString()}
                  </span>
                </div>
              </div>
            ))}
          </div>
        )}
      </div>
    </AdminPageShell>
  );
}
