// Source of truth for the list of providers the admin Scraper UI knows
// about, what fields each provider supports (Remote / Location / Mode /
// Max pages / Posted within), and the default values used when the user
// has not overridden them.
//
// Imported from both:
//   - app/(app)/admin/listings/listings-tabs.tsx (web admin)
//   - desktop/renderer/admin/pages/admin-listings-manual.tsx (desktop)
//
// The desktop renderer uses the supports* fields to gate which form
// inputs render per provider, matching the web admin exactly.

export type ManualProviderId =
  | 'careerbuilder'
  | 'builtin'
  | 'fantastic'
  | 'serpapi'
  | 'themuse'
  | 'welcometothejungle'
  | 'usajobs'
  | 'workatastartup'
  | 'weworkremotely'
  | 'remoteok'
  | 'jobicy'
  | 'remotive'
  | 'himalayas'
  | 'arbeitnow'
  | 'remotefirstjobs'
  | 'remotejobs-org'
  | 'clawjobs'
  | 'comeet-boards'
  | 'theirstack'
  | 'jobdataapi'
  | 'findwork'
  | 'adzuna'
  | 'jooble'
  | 'devitjobs'
  | 'workingnomads'
  | 'hackernews'
  | 'openjobs'
  | 'nodesk'
  | 'jobspresso'
  | 'python-org'
  | 'django-job-board'
  | 'greenhouse-boards'
  | 'lever-boards'
  | 'ashby-boards'
  | 'smartrecruiters-boards'
  | 'recruitee-boards'
  | 'workable-boards'
  | 'teamtailor-boards'
  | 'bamboohr-boards'
  | 'personio-boards'
  | 'pallet-boards'
  | 'pinpoint-boards'
  | 'workday-boards'
  | 'breezy-boards'
  | 'jobvite-boards'
  | 'jazzhr-boards'
  | 'crunchboard'
  | 'linkedin-guest'
  | 'indeed-scraper';

export interface ManualProviderOption {
  defaultMaxPages: number;
  defaultMode: 'backfill' | 'sync' | 'weekly';
  description: string;
  inheritGlobalLocation?: boolean;
  inheritGlobalMaxPages?: boolean;
  inheritGlobalSearch?: boolean;
  label: string;
  locationHint: string;
  locationLabel: string;
  maxPagesLabel?: string;
  maxPagesMax?: number;
  sourceSummary: string;
  supportsLocation: boolean;
  supportsMaxPages: boolean;
  supportsMode: boolean;
  supportsPostedWithin: boolean;
  supportsRemote: boolean;
  value: ManualProviderId;
}

export const MANUAL_PROVIDER_OPTIONS: ManualProviderOption[] = [
  // --- Highest volume: aggregators & bulk scrapers ---
  {
    defaultMaxPages: 10,
    defaultMode: 'sync',
    description:
      'Scrapes LinkedIn public guest API. No auth needed. 10 jobs/page, 2s delay between pages to avoid rate limits.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'LinkedIn (Guest)',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public scraper · ~400/run',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'linkedin-guest',
  },
  {
    defaultMaxPages: 10,
    defaultMode: 'sync',
    description:
      'Scrapes Indeed via headless Playwright browser. 25 jobs/page, 3s delay. No API key needed.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Indeed (Scraper)',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Playwright scraper · ~250/run',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'indeed-scraper',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'High-volume aggregated listings from ATS career pages. 50k jobs/mo budget.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Fantastic Jobs',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Aggregator API · ~10k+',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: true,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'fantastic',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'High-volume hiring signal API with fresh ATS-sourced postings. Uses 1 API credit/page; free plan is 200 credits/month.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'TheirStack',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    maxPagesLabel: 'API calls',
    maxPagesMax: 5,
    sourceSummary: 'Hiring signal API · 200/mo',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'theirstack',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from 60+ top tech companies using Greenhouse ATS. Databricks, Stripe, Okta, Airbnb, Anthropic, Elastic, Asana, Twilio, etc.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Greenhouse Boards',
    locationHint: 'All locations',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~8k+',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'greenhouse-boards',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'Large job aggregator pulling from Indeed, LinkedIn, ZipRecruiter and more.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Jooble',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Aggregator API · ~5k+',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'jooble',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'Paid ATS-sourced jobs feed with direct apply URLs, company logos, salary fields, and daily fresh listings. Requires JOBDATAAPI_KEY.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'JobDataAPI',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'ATS jobs API · very high volume',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'jobdataapi',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description: 'Google Jobs search results via SerpAPI. 5k searches/mo.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'SerpAPI',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Search API · ~5k',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'serpapi',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from 26 AI/tech companies using Ashby ATS. OpenAI, Notion, Ramp, Cohere, Cursor, etc.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Ashby Boards',
    locationHint: 'All locations',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~1.5k+',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'ashby-boards',
  },
  // --- Large: 1k–5k jobs ---
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Free tech job board with 3,000+ US listings, salary data, and tech stack tags.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'DevITjobs',
    locationHint: 'US only (auto-filtered)',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~3.4k',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'devitjobs',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'Global job search aggregator with salary data. 2,500 req/mo free tier.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Adzuna',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Search API · ~2.5k',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'adzuna',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description:
      'Large US jobs board with a public search API and real offsite apply links.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'CareerBuilder',
    locationHint: 'United States, city, or state',
    locationLabel: 'Location',
    sourceSummary: 'Public search API · ~2k',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'careerbuilder',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description:
      'Large public jobs directory with API-backed listing pages and ATS apply URLs.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'The Muse',
    locationHint: 'United States, city, or region',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~2k',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'themuse',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from 20+ top tech companies using Lever ATS. Netflix, Spotify, Cloudflare, etc.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Lever Boards',
    locationHint: 'All locations',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~1k+',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'lever-boards',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'Official government jobs source with query and location filters. Unlimited.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'USAJobs',
    locationHint: 'United States or region',
    locationLabel: 'Location',
    sourceSummary: 'Official API · ~1k+',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'usajobs',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from large enterprises using SmartRecruiters ATS. Visa (921+), Cisco, Capital One, etc.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'SmartRecruiters Boards',
    locationHint: 'All locations',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~1k+',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'smartrecruiters-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from companies using Recruitee public careers APIs.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Recruitee Boards',
    locationHint: 'All locations',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~50+',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'recruitee-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from companies using the Workable public widget API.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Workable Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~10 companies',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'workable-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from companies using public Teamtailor career sites.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Teamtailor Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~9 companies',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'teamtailor-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from companies using BambooHR public careers list.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'BambooHR Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~6 companies',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'bamboohr-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from companies using Personio public XML job feeds.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Personio Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS XML · ~8 companies',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'personio-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from community-curated Pallet job boards (Pioneer, Maven, etc.).',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Pallet Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public board API · ~5 boards',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'pallet-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape from companies using Pinpoint public job board JSON.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Pinpoint Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · ~5 companies',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'pinpoint-boards',
  },
  {
    defaultMaxPages: 2,
    defaultMode: 'sync',
    description:
      'Bulk scrape selected enterprise Workday CXS boards with public JSON endpoints.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Workday Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · enterprise',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'workday-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape selected Comeet Careers API boards with details, requirements, and hosted apply URLs.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Comeet Boards',
    locationHint: 'City, state, country, or Remote',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · selected boards',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'comeet-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Bulk scrape companies using BreezyHR public JSON career feeds.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'BreezyHR Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS API · selected boards',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'breezy-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Bulk scrape selected Jobvite-hosted public career boards.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Jobvite Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS HTML · selected boards',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'jobvite-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Bulk scrape selected JazzHR applytojob public career boards.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'JazzHR Boards',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public ATS HTML · selected boards',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'jazzhr-boards',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'TechCrunch CrunchBoard RSS feed — startup and tech jobs.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'CrunchBoard',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'RSS feed · single source',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'crunchboard',
  },
  // --- Medium: 100–1k jobs ---
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description:
      'Widely known US tech jobs board with detail-page apply links.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Built In',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Structured HTML · ~500',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'builtin',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description:
      'US-filtered public jobs index with downstream ATS apply URLs.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Welcome to the Jungle',
    locationHint: 'United States, city, or state',
    locationLabel: 'Location',
    sourceSummary: 'Public index · ~500',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'welcometothejungle',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description: 'US startup jobs from Y Combinator.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Work at a Startup',
    locationHint: 'City, state, remote region',
    locationLabel: 'Location',
    sourceSummary: 'Public HTML · ~300',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'workatastartup',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description:
      'Open-source static aggregator refreshed by GitHub Actions from hundreds of company sources.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'OpenJobs',
    locationHint: 'Keyword or location in listing URL',
    locationLabel: 'Location',
    maxPagesLabel: 'Batches',
    maxPagesMax: 4,
    sourceSummary: 'Static aggregator · ~200',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'openjobs',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description:
      'Curated remote jobs from Jobspresso using its public job-manager endpoint.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Jobspresso',
    locationHint: 'Remote region or country',
    locationLabel: 'Location',
    maxPagesLabel: 'Pages',
    maxPagesMax: 10,
    sourceSummary: 'Public job feed · ~1k+',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'jobspresso',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description: 'Remote jobs platform with search and pagination.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Himalayas',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~200',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'himalayas',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description: 'European-focused job board with US remote listings.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Arbeitnow',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~200',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'arbeitnow',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description: 'Remote-first jobs platform with search and pagination.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Remote First Jobs',
    locationHint: 'City, state, country',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~100',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'remotefirstjobs',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'Free RemoteJobs.org API with daily-updated remote postings, keyword search, and pagination.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'RemoteJobs.org',
    locationHint: 'Remote region or country',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~800+',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: false,
    value: 'remotejobs-org',
  },
  {
    defaultMaxPages: 5,
    defaultMode: 'sync',
    description:
      'Public ClawJobs feed with global listings, keyword search, remote filtering, and pagination.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'ClawJobs',
    locationHint: 'City, state, country, or Remote',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~40k+',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'clawjobs',
  },
  {
    defaultMaxPages: 3,
    defaultMode: 'sync',
    description:
      'Developer-focused Findwork job API with search and location filters. Requires FINDWORK_API_KEY.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Findwork',
    locationHint: 'City, state, country, or Remote',
    locationLabel: 'Location',
    sourceSummary: 'Developer jobs API · key required',
    supportsLocation: true,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: true,
    supportsRemote: true,
    value: 'findwork',
  },
  // --- Small: <100 jobs ---
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Remote jobs aggregator with a public JSON API.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Remote OK',
    locationHint: 'Remote only',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~97',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'remoteok',
  },
  {
    defaultMaxPages: 100,
    defaultMode: 'sync',
    description: 'Remote jobs board with a public REST API.',
    inheritGlobalLocation: false,
    inheritGlobalMaxPages: false,
    inheritGlobalSearch: true,
    label: 'Jobicy',
    locationHint: 'Remote only',
    locationLabel: 'Location',
    maxPagesLabel: 'Count',
    maxPagesMax: 100,
    sourceSummary: 'Public API · up to 100',
    supportsLocation: false,
    supportsMaxPages: true,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'jobicy',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Curated remote jobs board with a public REST API.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Remotive',
    locationHint: 'Remote only',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~50',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'remotive',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Remote-only jobs via RSS feed from We Work Remotely.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'We Work Remotely',
    locationHint: 'Remote only',
    locationLabel: 'Location',
    sourceSummary: 'RSS feed · ~50',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'weworkremotely',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Curated remote jobs with a public RSS feed.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'NoDesk',
    locationHint: 'Remote only',
    locationLabel: 'Location',
    sourceSummary: 'RSS feed · ~100',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'nodesk',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Python-focused jobs from the official Python.org RSS feed.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Python.org Jobs',
    locationHint: 'Remote, city, or country',
    locationLabel: 'Location',
    sourceSummary: 'Official RSS · ~25',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'python-org',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Django and Python roles from the Django Job Board RSS feed.',
    inheritGlobalLocation: true,
    inheritGlobalSearch: true,
    label: 'Django Job Board',
    locationHint: 'Remote, city, or country',
    locationLabel: 'Location',
    sourceSummary: 'RSS feed · ~25',
    supportsLocation: true,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: true,
    value: 'django-job-board',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'YC startup jobs from Hacker News. Free Firebase API.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Hacker News',
    locationHint: 'US startups',
    locationLabel: 'Location',
    sourceSummary: 'Firebase API · ~31',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'hackernews',
  },
  {
    defaultMaxPages: 1,
    defaultMode: 'sync',
    description: 'Curated remote jobs board.',
    inheritGlobalLocation: false,
    inheritGlobalSearch: true,
    label: 'Working Nomads',
    locationHint: 'Remote only',
    locationLabel: 'Location',
    sourceSummary: 'Public API · ~30',
    supportsLocation: false,
    supportsMaxPages: false,
    supportsMode: false,
    supportsPostedWithin: false,
    supportsRemote: false,
    value: 'workingnomads',
  },
];

// Fast O(1) lookup by provider id. Both the web admin and the desktop
// renderer match a row's runtime `provider` string against this map to
// find which fields the provider supports.
export const MANUAL_PROVIDER_OPTIONS_BY_ID: Readonly<
  Record<string, ManualProviderOption>
> = MANUAL_PROVIDER_OPTIONS.reduce<Record<string, ManualProviderOption>>(
  (acc, option) => {
    acc[option.value] = option;
    return acc;
  },
  {},
);
